name: ausweisapp2-ce
title: AusweisApp2 Community Edition
version: '1.14.3'
base: core18
summary: AusweisApp2-CE - Tool for the german nPA (Community Edition)
description: |
  The AusweisApp2 (since November 2014 successor of the AusweisApp) is
  a free application software for the PC to use electronic authentication
  via the Internet with the new German identity card and the electronic
  residence permit or their online identification function. This makes
  it possible for citizens in Germany to identify themselves easily and
  securely on the Internet - for example, to deal with administrative
  formalities online.

  The software establishes an encrypted connection between the identity
  card or the electronic residence permit, the card reader and the eID
  server on the other side. The IDApp2 serves to securely perform the
  procedure of certificate and authenticity checks and to offer the
  citizen an interface for using the online ID function.

  http://www.ausweisapp.bund.de

architectures: 
  - amd64

licence : EUPL-1.1

icon: snap/gui/icon.svg

grade: classic
confinement: strict

parts:
  desktop-qt5:
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    make-parameters:
    - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    
  ausweisapp2:
    plugin: cmake
    configflags: [-DCMAKE_BUILD_TYPE=RELEASE, -DCMAKE_INSTALL_PREFIX=/usr/]
    source-type: tar
    source: https://github.com/Governikus/AusweisApp2/releases/download/1.14.3/AusweisApp2-1.14.3.tar.gz

    override-build: |
      cd /root/parts/ausweisapp2/src
      patch -p1 < /root/project/patches/AusweisApp2-snapcraft.patch
      cd /root
      snapcraftctl build
      strip /root/parts/ausweisapp2/install/usr/bin/AusweisApp2
      rm -r /root/parts/ausweisapp2/install/usr/bin/lib* /root/parts/ausweisapp2/install/usr/bin/X11 /root/parts/ausweisapp2/install/usr/share/doc

    build-packages:
      - cmake
      - file
      - pkg-config
      - g++
      - qtbase5-dev
      - libqt5svg5-dev
      - qttools5-dev
      - libqt5websockets5-dev
      - qtconnectivity5-dev
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
      - libssl-dev
      - libpcsclite-dev
      - libudev-dev
      - libhttp-parser-dev

    stage-packages:
      - libqt5svg5
      - libqt5websockets5
      - libqt5xml5
      - libhttp-parser-dev

    after: [desktop-qt5]

apps:
  ausweisapp2-ce:
    command: desktop-launch $SNAP/usr/bin/AusweisApp2
    desktop: usr/share/applications/AusweisApp2.desktop

    plugs:
      - desktop
      - unity7
      - network
      - network-bind
      - home
      - hardware-observe

